openapi: 3.0.3
info:
  title: Waku V2 node REST API
  version: 1.0.0
  contact:
    name: VAC Team
    url: https://forum.vac.dev/
tags:
  - name: admin
    description: Admin REST API for WakuV2 node
paths:
  /admin/v1/peers:
    $ref: "./adminapi.yaml"
  /debug/v1/info:
     $ref: "./debugapi_info.yaml"
  /debug/v1/version:
     $ref: "./debugapi_version.yaml"
  /health:
    $ref: "./healthapi.yaml"
  /lightpush/v1/message:
    $ref: "./lightpushapi.yaml"
  /relay/v1/messages/{pubsubTopic}:
    $ref: "./relayapi_messages.yaml"
  /relay/v1/subscriptions:
    $ref: "./relayapi_subscriptions.yaml"
  /relay/v1/auto/messages/{contentTopic}:
    $ref: "./relayapi_auto_content_topic.yaml"
  /relay/v1/auto/messages:
    $ref: "./relayapi_auto_messages.yaml"
  /relay/v1/auto/subscriptions:
    $ref: "./relayapi_auto_subscriptions.yaml"
  /store/v1/messages:
    $ref: "./storeapi.yaml"
  /filter/v1/subscriptions:
    $ref: "./filterapi_v1_subscriptions.yaml"
  /filter/v1/messages/{contentTopic}:
    $ref: "./filterapi_v1_messages.yaml"
  /filter/v2/subscriptions/{requestId}:
    $ref: "./filterapi_v2_subscription_ping.yaml"
  /filter/v2/subscriptions:
    $ref: "./filterapi_v2_subscriptions.yaml"
  /filter/v2/subscriptions/all:
    $ref: "./filterapi_v2_subscriptions_all.yaml"
  /filter/v2/messages/{contentTopic}:
    $ref: "./filterapi_v2_messages.yaml"
components:
  schemas:
    $ref: "./schemas/apitypes.yaml"
